<a href="https://colab.research.google.com/github/NeagrTavakol/Final_dataminning/blob/main/Final_projet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
#mount drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


read dev dataset

In [ ]:
dev_csv="/content/drive/MyDrive/Colab Notebooks/dev.csv"
dev_df = pd.read_csv(dev_csv,sep='\t')
dev_df=dev_df.drop("Unnamed: 0",axis=1)
dev_columns=dev_df.columns

read train dataset

In [ ]:
train_csv="/content/drive/MyDrive/Colab Notebooks/train.csv"
train_df = pd.read_csv(train_csv,sep='\t')
train_df=train_df.drop("Unnamed: 0",axis=1)
train_columns = train_df.columns

## **Tokenize Data**

**install packages**

In [ ]:
# Install; note that the prefix "!" is not needed if you are running in a terminal
!pip install stanza

# Import the package
import stanza

     |████████████████████████████████| 432 kB 5.4 MB/s 
     |████████████████████████████████| 174 kB 54.7 MB/s 
  Created wheel for emoji: filename=emoji-1.6.3-py3-none-any.whl size=170298 sha256=0155812afc46baffa28bfea6005de94a722f018506d957a421eddc6f692bb141
  Stored in directory: /root/.cache/pip/wheels/03/8b/d7/ad579fbef83c287215c0caab60fb0ae0f30c4d7ce5f580eade
Successfully built emoji


In [ ]:
# Download an Persiabn model into the default directory
print("Downloading Persian model...")
stanza.download('fa')

2022-01-26 07:20:44 INFO: Downloading default packages for language: fa (Persian)...


2022-01-26 07:20:50 INFO: Finished downloading models and saved to /root/stanza_resources.


**create models**

In [ ]:
# Build a Persian pipeline, with all processors by default
print("Building a Persian pipeline...")
fa_nlp = stanza.Pipeline('fa')

2022-01-26 07:46:57 INFO: Loading these models for language: fa (Persian):
| Processor | Package |
-----------------------
| tokenize  | perdt   |
| mwt       | perdt   |
| pos       | perdt   |
| lemma     | perdt   |
| depparse  | perdt   |

2022-01-26 07:46:57 INFO: Use device: cpu
2022-01-26 07:46:57 INFO: Loading: tokenize
2022-01-26 07:46:57 INFO: Loading: mwt
2022-01-26 07:46:57 INFO: Loading: pos


Building a Persian pipeline...


2022-01-26 07:46:58 INFO: Loading: lemma
2022-01-26 07:46:58 INFO: Loading: depparse
2022-01-26 07:46:59 INFO: Done loading processors!


**find tokens of dataframe and save in array**

In [ ]:
# test_token_df['tokenized_sents'] = test_token_df.apply(lambda row: fa_nlp(row['comment']).sentences.words.text, axis=1)
tokenized_array=[]
for i in range(0,len(train_df)):
  comment=train_df.iloc[i]["comment"]
  tokenized_comment = fa_nlp(comment)
  tokens_array=[]
  for i,sent in enumerate(tokenized_comment.sentences):
    for word in sent.words:
      tokens_array.append(word.text)
  tokenized_array.append(tokens_array)
#word.text, word.lemma, word.pos, word.head, word.deprel))

In [ ]:
#find tokens of rest of dataset (process interupted cause of volume of dataset)
# rest_train_df=train_df[52466:]
for i in range(52466,len(train_df)):
  comment=train_df.iloc[i]["comment"]
  tokenized_comment = fa_nlp(comment)
  tokens_array=[]
  for i,sent in enumerate(tokenized_comment.sentences):
    for word in sent.words:
      tokens_array.append(word.text)
  tokenized_array.append(tokens_array)

/usr/local/lib/python3.7/dist-packages/stanza/models/common/beam.py:86: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  prevK = bestScoresId // numWords


**save tokens array to csv file**

In [ ]:
#save tokens to array
import csv
with open('tokens_array.csv', 'w', newline='') as file:
    mywriter = csv.writer(file, delimiter=',')
    mywriter.writerows(tokenized_array)

**convert tokens array to dataframe **

In [ ]:
# convert tokenized_array to dataframe
tokenized_df=pd.DataFrame(tokenized_array)

**save dataframe to csv file**

In [ ]:
#save dataframe 
tokenized_df.to_csv('tokens_df.csv')

In [ ]:
# with open('tokens_array.csv', 'r', newline='') as file:
#   myreader = csv.reader(file, delimiter=',')
#   for rows in myreader:
#     print(rows)

**### another tokenizer**

In [ ]:
# !pip3 install parsivar
# !pip uninstall parsivary

In [ ]:
# for i in tokens_arr[:10]:
#   print(i,len(i),type(i))

In [ ]:
# from parsivar import Normalizer
# from parsivar import Tokenizer
# fa_normalizer = Normalizer()
# fa_tokenizer = Tokenizer()

In [ ]:
# fa_tokens_array=[]
# for i in range(20,40):
#   comment=train_df.iloc[i]["comment"]
#   t=fa_tokenizer.tokenize_words(comment)
#   comment=fa_normalizer.normalize(comment)
#   t=fa_tokenizer.tokenize_words(comment)
#   tokenized_comment = fa_tokenizer.tokenize_words(comment)
#   tokens_array=[]
#   for i in tokenized_comment:
#     tokens_array.append(i)
#   fa_tokens_array.append(tokens_array)

## **Read tokenized dataet**

In [ ]:
#read dataframe csv file
# tokens_dataframe=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/tokens_df.csv")
# tokens_dataframe=tokens_dataframe.drop("Unnamed: 0",axis=1)
# #tokens_dataframe[52000:52050]

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342

In [ ]:
# arr=tokens_dataframe.to_numpy()
# tokens_arr=[]
# for i in arr :
#   sentense=[]
#   for word in i:
#     if type(word) is str:
#       sentense.append(word)
#   tokens_arr.append(sentense)

**read from array csv file (smaller size)**

تو از اینجا ران کن(فایلش رو تلگرام فرستادم برات)

In [8]:
#read array csv file
tokens_array=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/tokens_array.csv",sep='\t',header=None)
# tokens_array.head()

In [9]:
from types import new_class
# from string import punctuation
import re

punctuation=['!','"','#','$','%','&',"'",'(',')','*','+','،','-','.',','"/",':',';','<','=','>','?','@','[',"\\","]","^",'_','`','{','|','}','~']
# tokens_array.to_numpy()
tokens_arr=[]
for i in tokens_array.to_numpy():
  sent=[]
  for j in i[0].split(','):
    if j not in punctuation:
      sent.append(j)
  tokens_arr.append(sent)

In [ ]:
for i in tokens_arr[:10]:
  print(i)

## **Preproccessing**

**Analyze Reviews Length**

In [10]:
import matplotlib.pyplot as plt
reviews_len = [len(x) for x in tokens_arr]
reviews_len=np.array(reviews_len)

In [ ]:
# pd.Series(tokens_arr).hist()
# plt.show()
# pd.Series(tokens_arr).describe()

In [11]:
print("min:",reviews_len.min(),"max:",reviews_len.max(),"min:",reviews_len.mean(),"len:",len(reviews_len))

min: 3 max: 362 min: 19.003015873015872 len: 56700


In [7]:
# for i in range(6,29):
print(np.count_nonzero(reviews_len > 75))

689


remove outliers

In [12]:
cleaned_rokens_arr=[x for x in tokens_arr if len(x)<75]
print(len(cleaned_rokens_arr))

55978


In [13]:
!pip uninstall hazm

In [ ]:
# from __future__ import unicode_literals
# from hazm import *

In [10]:
# normalizer = Normalizer()
# n=normalizer.normalize('چقَدررررِرررررر   رر')
# print(n)

save in csv

## **Word embedding**

In [18]:
from gensim.models import Word2Vec

word2vec = Word2Vec(cleaned_rokens_arr, min_count=5,size=100)

In [19]:
len(cleaned_rokens_arr)

55978

**calculate vacors for each word**

In [16]:
# word_vectors=word2vec[word2vec.wv]

In [ ]:
len(word_vectors)

In [ ]:
word_vectors[:1]

In [21]:
vocabulary = word2vec.wv.vocab
embedded_array=[]
for sent in cleaned_rokens_arr:
  # vec_vocab = []
  vec_vocab=[word2vec.wv[word] for word in sent if word in vocabulary]
  # for word in sent:
  #   if word in vocabulary:
  #     vector = word2vec.wv[word]
      # vec_vocab.append(vector)
  embedded_array.append(vec_vocab)

In [24]:
for i in range(0,1):
  print((embedded_array[i]))#,len(cleaned_rokens_arr[i]))

[array([ 9.18136597e-01, -2.01507068e+00, -8.35926771e-01,  2.29304403e-01,
        1.97068202e+00,  7.03686535e-01, -5.60263038e-01,  9.53287184e-02,
        1.23877442e+00, -9.99239311e-02,  1.86079055e-01, -3.07716638e-01,
       -1.31347024e+00, -3.18798810e-01, -7.84592688e-01, -8.33475530e-01,
        2.25119725e-01, -1.64235210e+00,  1.13527489e+00,  7.68735826e-01,
       -9.09053683e-01, -6.48629367e-01,  3.41588944e-01, -4.19738799e-01,
        7.04144120e-01, -5.51296651e-01, -5.16874969e-01, -7.71014392e-01,
       -4.98344034e-01,  3.31717938e-01, -1.63022447e+00, -1.00255978e+00,
       -3.62743229e-01,  4.73100156e-01,  4.58315820e-01, -6.88461781e-01,
       -6.53263807e-01,  1.26591936e-01, -5.95885873e-01,  1.02371812e+00,
       -2.72593379e-01,  9.09261763e-01, -6.85493410e-01, -1.18711852e-01,
       -7.21120059e-01,  2.08592236e-01,  2.82373965e-01,  9.15133357e-01,
        1.38338730e-01,  1.14106202e+00,  1.13924503e+00,  9.26295295e-04,
        2.56397575e-01, 

save embedded words in csv file(too large!)>500mb

In [ ]:
# #save tokens to array
# import csv
# with open('embedded_array.csv', 'w', newline='') as file:
#     mywriter = csv.writer(file, delimiter=',')
#     mywriter.writerows(embedded_array)

add padding to short comemnts

In [ ]:
import math
padded_posts = []
print(len(vec_vocab))
for post in [vec_vocab]:
    # print(post)
    # Pad short posts with alternating min/max
    print(len(post))
    if len(post) < 20:
        print(" in if")
        
        # # Method 1
        # print(type(post))
        # pointwise_min = np.minimum.reduce(np.any(post, axis=1))
        # m=min(post)
        # pointwise_max = np.maximum.reduce(post)
        # padding = [pointwise_max, pointwise_min]
        
        # Method 2
        pointwise_avg = np.mean(post)
        padding = [pointwise_avg]
        print(pointwise_avg)
        print(padding)

        # post += padding * math.ceil((20 - len(post) / 2.0))
        post += padding*(20-len(post))
        print(len(post))
    print(len(post))    
    # Shorten long posts or those odd number length posts we padded to 51
    if len(post) > 20:
        post = post[:20]
    
    # Add the post to our new list of padded posts
    padded_posts.append(post)

In [ ]:
import io
import re
import string
import tqdm

import numpy as np

import tensorflow as tf
from tensorflow.keras import layers

In [ ]:
# Load the TensorBoard notebook extension
%load_ext tensorboard

In [ ]:
SEED = 42
AUTOTUNE = tf.data.AUTOTUNE

## **Traingin LSTM**

In [ ]:
len(embedded_array[:1][0][0])

100

import tensowerflow

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.7.0


In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.python.keras.layers import Input
#,a LSTM, Bidirectional, Dense, Embedding

In [ ]:
x=embedded_array[:1]
y=[]
x_train = sequence.pad_sequences(x, maxlen=100)
y.append(x_train)
print(x_train)

[[[ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 1  0 -2 ...  1  0  0]
  [ 0  0  0 ...  0  0  0]]]
