<a href="https://colab.research.google.com/github/NeagrTavakol/Final_dataminning/blob/main/Final_projet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
#mount drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


read dev dataset

In [9]:
dev_csv="/content/drive/MyDrive/Colab Notebooks/dev.csv"
dev_df = pd.read_csv(dev_csv,sep='\t')
dev_df=dev_df.drop("Unnamed: 0",axis=1)
dev_columns=dev_df.columns

read train dataset

In [10]:
train_csv="/content/drive/MyDrive/Colab Notebooks/train.csv"
train_df = pd.read_csv(train_csv,sep='\t')
train_df=train_df.drop("Unnamed: 0",axis=1)
train_columns = train_df.columns

## **Tokenize Data**

**install packages**

In [6]:
# Install; note that the prefix "!" is not needed if you are running in a terminal
!pip install stanza

# Import the package
import stanza

     |████████████████████████████████| 432 kB 4.3 MB/s 
     |████████████████████████████████| 174 kB 48.3 MB/s 
  Created wheel for emoji: filename=emoji-1.6.3-py3-none-any.whl size=170298 sha256=5956e340f2236efab06f4d9da57ce6bffb2447f632b8d35d356b9a1130df1643
  Stored in directory: /root/.cache/pip/wheels/03/8b/d7/ad579fbef83c287215c0caab60fb0ae0f30c4d7ce5f580eade
Successfully built emoji


In [7]:
# Download an Persiabn model into the default directory
print("Downloading Persian model...")
stanza.download('fa')

2022-01-27 17:28:17 INFO: Downloading default packages for language: fa (Persian)...


2022-01-27 17:28:38 INFO: Finished downloading models and saved to /root/stanza_resources.


**create models**

In [8]:
# Build a Persian pipeline, with all processors by default
print("Building a Persian pipeline...")
fa_nlp = stanza.Pipeline('fa')

2022-01-27 17:28:41 INFO: Loading these models for language: fa (Persian):
| Processor | Package |
-----------------------
| tokenize  | perdt   |
| mwt       | perdt   |
| pos       | perdt   |
| lemma     | perdt   |
| depparse  | perdt   |

2022-01-27 17:28:41 INFO: Use device: cpu
2022-01-27 17:28:41 INFO: Loading: tokenize


Building a Persian pipeline...


2022-01-27 17:28:41 INFO: Loading: mwt
2022-01-27 17:28:41 INFO: Loading: pos
2022-01-27 17:28:42 INFO: Loading: lemma
2022-01-27 17:28:42 INFO: Loading: depparse
2022-01-27 17:28:43 INFO: Done loading processors!


**find tokens of dataframe and save in array**

In [9]:
# test_token_df['tokenized_sents'] = test_token_df.apply(lambda row: fa_nlp(row['comment']).sentences.words.text, axis=1)
tokenized_array=[]
for i in range(0,len(train_df)):
  comment=train_df.iloc[i]["comment"]
  tokenized_comment = fa_nlp(comment)
  tokens_array=[]
  for i,sent in enumerate(tokenized_comment.sentences):
    for word in sent.words:
      tokens_array.append(word.text)
  tokenized_array.append(tokens_array)
#word.text, word.lemma, word.pos, word.head, word.deprel))

/usr/local/lib/python3.7/dist-packages/stanza/models/common/beam.py:86: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  prevK = bestScoresId // numWords


KeyboardInterrupt: ignored

In [ ]:
#find tokens of rest of dataset (process interupted cause of volume of dataset)
# rest_train_df=train_df[52466:]
for i in range(52466,len(train_df)):
  comment=train_df.iloc[i]["comment"]
  tokenized_comment = fa_nlp(comment)
  tokens_array=[]
  for i,sent in enumerate(tokenized_comment.sentences):
    for word in sent.words:
      tokens_array.append(word.text)
  tokenized_array.append(tokens_array)

/usr/local/lib/python3.7/dist-packages/stanza/models/common/beam.py:86: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  prevK = bestScoresId // numWords


**save tokens array to csv file**

In [ ]:
#save tokens to array
import csv
with open('tokens_array.csv', 'w', newline='') as file:
    mywriter = csv.writer(file, delimiter=',')
    mywriter.writerows(tokenized_array)

**convert tokens array to dataframe **

In [ ]:
# convert tokenized_array to dataframe
tokenized_df=pd.DataFrame(tokenized_array)

**save dataframe to csv file**

In [ ]:
#save dataframe 
tokenized_df.to_csv('tokens_df.csv')

In [ ]:
# with open('tokens_array.csv', 'r', newline='') as file:
#   myreader = csv.reader(file, delimiter=',')
#   for rows in myreader:
#     print(rows)

**### another tokenizer**

In [ ]:
# !pip3 install parsivar
# !pip uninstall parsivary

In [ ]:
# for i in tokens_arr[:10]:
#   print(i,len(i),type(i))

In [ ]:
# from parsivar import Normalizer
# from parsivar import Tokenizer
# fa_normalizer = Normalizer()
# fa_tokenizer = Tokenizer()

In [ ]:
# fa_tokens_array=[]
# for i in range(20,40):
#   comment=train_df.iloc[i]["comment"]
#   t=fa_tokenizer.tokenize_words(comment)
#   comment=fa_normalizer.normalize(comment)
#   t=fa_tokenizer.tokenize_words(comment)
#   tokenized_comment = fa_tokenizer.tokenize_words(comment)
#   tokens_array=[]
#   for i in tokenized_comment:
#     tokens_array.append(i)
#   fa_tokens_array.append(tokens_array)

## **Read tokenized dataet**

In [ ]:
#read dataframe csv file
# tokens_dataframe=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/tokens_df.csv")
# tokens_dataframe=tokens_dataframe.drop("Unnamed: 0",axis=1)
# #tokens_dataframe[52000:52050]

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342

In [ ]:
# arr=tokens_dataframe.to_numpy()
# tokens_arr=[]
# for i in arr :
#   sentense=[]
#   for word in i:
#     if type(word) is str:
#       sentense.append(word)
#   tokens_arr.append(sentense)

**read from array csv file (smaller size)**

تو از اینجا ران کن(فایلش رو تلگرام فرستادم برات)

In [11]:
#read array csv file
tokens_array=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/tokens_array.csv",sep='\t',header=None)
# tokens_array.head()

In [12]:
from types import new_class
# from string import punctuation
import re

punctuation=['!','"','#','$','%','&',"'",'(',')','*','+','،','-','.',','"/",':',';','<','=','>','?','@','[',"\\","]","^",'_','`','{','|','}','~']
# tokens_array.to_numpy()
tokens_arr=[]
for i in tokens_array.to_numpy():
  sent=[]
  for j in i[0].split(','):
    if j not in punctuation:
      sent.append(j)
  tokens_arr.append(sent)

In [13]:
for i in tokens_arr[:10]:
  print(i)

['واقعا', 'حیف', 'وقت', 'که', 'بنویسم', 'سرویس', 'دهیتون', 'شده', 'افتضاح']
['قرار', 'بود', '۱', 'ساعته', 'برسه', 'ولی', 'نیم', 'ساعت', 'زودتر', 'از', 'موقع', 'رسید', 'شما', 'ببین', 'چقدرررررررررررر', 'پلاک', 'خفنههههه', 'من', 'سالها', 'ست', 'مشتریشونم', 'و', 'سالها', 'ست', 'مزه', 'بهشت', 'میده', 'غذاشون']
['قیمت', 'این', 'مدل', 'اصلا', 'با', 'کیفیتش', 'سازگاری', 'نداره', 'فقط', 'ظاهر', 'فریبنده', 'داره', 'پرش', 'میکنن', 'کالباس', 'و', 'قارچ']
['عالللی', 'بود', 'همه', 'چه', 'درست', 'و', 'به', 'اندازه', 'و', 'کیفیت', 'خوب', 'امیداورم', 'همیشه', 'کیفیتتون', 'خوب', 'باشه', 'ما', 'مشتری', 'همیشگی', 'بشیم']
['شیرینی', 'وانیلی', 'فقط', 'یک', 'مدل', 'بود']
['بدترین', 'پیتزایی', 'که', 'تا', 'به', 'حال', 'خورده', 'بودم']
['از', 'همه', 'لحاظ', 'عالی', 'ممنون', 'م']
['کیفیت', 'غذا', 'متوسط', 'رو', 'به', 'پایین', 'بود', 'انگار', 'داخل', 'یه', 'رستوران', 'معمولی', 'غذا', 'خوردی', 'درحالی', 'که', 'امتیاز', 'رستوران', 'در', 'اسنپ', 'فود', '۴٫۳', 'بود']
['همه', 'اقلام', 'تازه', 'و', 'به', 'روز', 'وخیل

## **Preproccessing**

**Analyze Reviews Length**

In [13]:
import matplotlib.pyplot as plt
reviews_len = [len(x) for x in tokens_arr]
reviews_len=np.array(reviews_len)

In [14]:
# pd.Series(tokens_arr).hist()
# plt.show()
# pd.Series(tokens_arr).describe()

In [15]:
print("min:",reviews_len.min(),"max:",reviews_len.max(),"min:",reviews_len.mean(),"len:",len(reviews_len))

min: 3 max: 362 min: 19.003015873015872 len: 56700


In [16]:
# for i in range(6,29):
print(np.count_nonzero(reviews_len > 75))

689


remove outliers

In [6]:
cleaned_rokens_arr=[x for x in tokens_arr if len(x)<75]
print(len(cleaned_rokens_arr))

NameError: ignored

In [18]:
!pip uninstall hazm

In [ ]:
# from __future__ import unicode_literals
# from hazm import *

In [ ]:
# normalizer = Normalizer()
# n=normalizer.normalize('چقَدررررِرررررر   رر')
# print(n)

save in csv

ثریا 
اینجا کد ورد امبدنیگ رو میتونی ببینی 
کلمات مختلفی هم باهاش امتحان کردم اوکی شد

## **Word embedding**

In [4]:
!pip install gensim
# !pip install nltk

In [22]:
#for_test_for_word_embedding
# import gensim
# from gensim.models import Word2Vec
# from nltk.tokenize import sent_tokenize, word_tokenize
# import pandas as pd


# rev.head()
# corpus_text = 'n'.join(rev[:1000]['Text'])
# data = []
# # iterate through each sentence in the file
# for i in sent_tokenize(corpus_text):
#     temp = []
#     # tokenize the sentence into words
#     for j in word_tokenize(i):
#         temp.append(j.lower())
#     data.append(temp)

# word2vec= gensim.models.Word2Vec(data, min_count=5,size=100)
# word2vec = Word2Vec(cleaned_rokens_arr, min_count=5,size=100)
# کد بالایی ها رو فعلا بذار باشه و اینکه کامنت باشه  
#main_code
import gensim
from gensim.models import KeyedVectors
model = KeyedVectors.load_word2vec_format('/content/drive/MyDrive/Colab Notebooks/model.bin', binary=True)

In [23]:
vector = model['خوب']
# see the shape of the vector (300,)
vector.shape

(100,)

In [26]:
model.most_similar('بهتر')

[('.بهتر', 0.8202100992202759),
 ('مناسبتر', 0.7822331190109253),
 ('مفیدتر', 0.7766575217247009),
 ('خوب', 0.7656928300857544),
 ('وبهتر', 0.7652808427810669),
 ('راحتر', 0.7449773550033569),
 ('راحتتر', 0.7429759502410889),
 ('..بهتر', 0.73868727684021),
 ('-بهتر', 0.7375583052635193),
 ('!بهتر', 0.7351512908935547)]

In [27]:
model.most_similar('طعم')

[('مزه', 0.8385604023933411),
 ('وطعم', 0.8267494440078735),
 ('طعمی', 0.8193885684013367),
 ('.طعم', 0.7970529198646545),
 ('ترش', 0.7735953330993652),
 ('گَس', 0.755219042301178),
 ('طعمش', 0.7514316439628601),
 ('داژه', 0.7506887316703796),
 ('ترشی', 0.7470675706863403),
 ('گرانولا', 0.7449643611907959)]

In [20]:
len(cleaned_rokens_arr)

55978

**calculate vacors for each word**

In [ ]:
# word_vectors=word2vec[word2vec.wv]

In [1]:
# len(word_vectors)

In [2]:
# word_vectors[:1]

In [22]:
vocabulary = word2vec.wv.vocab
embedded_array=[]
for sent in cleaned_rokens_arr:
  # vec_vocab = []
  vec_vocab=[word2vec.wv[word] for word in sent if word in vocabulary]
  # for word in sent:
  #   if word in vocabulary:
  #     vector = word2vec.wv[word]
      # vec_vocab.append(vector)
  embedded_array.append(vec_vocab)

In [ ]:
for i in range(0,1):
  print((embedded_array[i]))#,len(cleaned_rokens_arr[i]))

In [27]:
#for test
# import numpy as np
# import pickle

# import sys
# import os

# from keras.preprocessing.sequence import pad_sequences
# from keras.utils.np_utils import to_categorical

# from keras.layers import Embedding
# from keras.layers import Dense, Input
# from keras.layers import TimeDistributed
# from keras.layers import LSTM, Bidirectional
# from keras.models import Model
# embedding_layer = Embedding(len(word2int) + 1,
#                             EMBEDDING_DIM,
#                             weights=[embedding_matrix],
#                             input_length=30,
#                             trainable=True)
# sequence_input = Input(shape=(30,), dtype='int32')
# embedded_sequences = embedding_layer(sequence_input)
# l_lstm = Bidirectional(LSTM(69, return_sequences=True))(embedded_sequences)

save embedded words in csv file(too large!)>500mb

In [ ]:
# #save tokens to array
# import csv
# with open('embedded_array.csv', 'w', newline='') as file:
#     mywriter = csv.writer(file, delimiter=',')
#     mywriter.writerows(embedded_array)

add padding to short comemnts

In [ ]:
import math
padded_posts = []
print(len(vec_vocab))
for post in [vec_vocab]:
    # print(post)
    # Pad short posts with alternating min/max
    print(len(post))
    if len(post) < 20:
        print(" in if")
        
        # # Method 1
        # print(type(post))
        # pointwise_min = np.minimum.reduce(np.any(post, axis=1))
        # m=min(post)
        # pointwise_max = np.maximum.reduce(post)
        # padding = [pointwise_max, pointwise_min]
        
        # Method 2
        pointwise_avg = np.mean(post)
        padding = [pointwise_avg]
        print(pointwise_avg)
        print(padding)

        # post += padding * math.ceil((20 - len(post) / 2.0))
        post += padding*(20-len(post))
        print(len(post))
    print(len(post))    
    # Shorten long posts or those odd number length posts we padded to 51
    if len(post) > 20:
        post = post[:20]
    
    # Add the post to our new list of padded posts
    padded_posts.append(post)

In [ ]:
import io
import re
import string
import tqdm

import numpy as np

import tensorflow as tf
from tensorflow.keras import layers

In [ ]:
# Load the TensorBoard notebook extension
%load_ext tensorboard

In [ ]:
SEED = 42
AUTOTUNE = tf.data.AUTOTUNE

## **Traingin LSTM**

In [ ]:
len(embedded_array[:1][0][0])

100

import tensowerflow

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.7.0


In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.python.keras.layers import Input
#,a LSTM, Bidirectional, Dense, Embedding

In [ ]:
x=embedded_array[:1]
y=[]
x_train = sequence.pad_sequences(x, maxlen=100)
y.append(x_train)
print(x_train)

[[[ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 1  0 -2 ...  1  0  0]
  [ 0  0  0 ...  0  0  0]]]
